# Generated by Django 5.0.7 on 2024-07-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('priority', models.CharField(max_length=50)),
                ('difficulty', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wake_up_time', models.TimeField()),
                ('sleep_time', models.TimeField()),
                ('productive_hours', models.CharField(max_length=255)),
                ('preferred_categories', models.CharField(max_length=255)),
                ('study_duration', models.IntegerField()),
                ('study_environment', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
                ('year_of_study', models.CharField(max_length=50)),
                ('recurring_commitments', models.TextField()),
                ('learning_style', models.CharField(max_length=255)),
                ('short_term_goals', models.TextField()),
                ('long_term_goals', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
