# Generated by Django 5.0.7 on 2024-07-20 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_style',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='long_term_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='major',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='recurring_commitments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='short_term_goals',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='study_duration',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='study_environment',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='year_of_study',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wake_up_time',
            field=models.CharField(max_length=255),
        ),
    ]
